/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package somelib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String getHelloWorld() {
        return "Hello fucking world";
    }
}
